Favorites CRD
QimbE/AudioBase pull request #42
Opened 2024-04-02 18:55 UTC by likeitbro

Похоже у меня процветает деменция, но я на тесты и фиксы потратил слишком много времени (хотя там вроде изи). То нулевой гуид кинет летальное исключение, то у меня allow anonymous стоит...

2024-04-02 19:17 UTC, QimbE requested changes

2024-04-02 19:17 UTC, QimbE commented on Application/Favorites/CreateFavorite/CreateFavoriteCommand.cs
> +public record CreateFavoriteCommand(Guid UserId, Guid TrackId): IRequest<Result<bool>>;
Как будто логичнее назвать "Add", а не "Create"

2024-04-02 19:17 UTC, QimbE commented on Application/Favorites/CreateFavorite/CreateFavoriteCommandHandler.cs
> +        User? user = _context.Users.FirstOrDefaultAsync(u => u.Id == request.UserId).Result;
WTF? Это что за пьяное программирование? Везде на вот так надо поменять.
```suggestion
        User? user = await _context.Users.FirstOrDefaultAsync(u => u.Id == request.UserId);
```

2024-04-02 19:17 UTC, QimbE commented on Application/GraphQL/TypeConfigurations/FavoriteType.cs
> +    }
Зачем? Можно же в таком случае просто унаследоваться. В обоих местах лучше поменяй.

2024-04-02 19:17 UTC, QimbE commented on Domain/Tracks/Track.cs
> +    }*/
лучше просто удали)

2024-04-02 19:17 UTC, QimbE commented on Presentation/Endpoints/Favorites.cs
> +                    , CancellationToken cancellationToken) =>
запятая - мое почтение

2024-04-03 08:47 UTC, likeitbro commented on Application/Favorites/CreateFavorite/CreateFavoriteCommandHandler.cs
> +        User? user = _context.Users.FirstOrDefaultAsync(u => u.Id == request.UserId).Result;
На улице апрель, а новый год будто бы вчера

2024-04-03 08:52 UTC, QimbE approved these changes

2024-04-03 08:56 UTC, merged